## Default Functions

In [240]:

import numpy as np
from scipy.stats import binom


def callPayoff(spot, strike):
    return np.maximum(spot - strike, 0.0)


def putPayoff(spot, strike):
    return np.maximum(strike - spot, 0.0)

def euroBinomPricerRecursive(S, K, r, v, q, T, n, payoff, verbose = True):
    nodes = n  + 1
    h = T / n
    u = np.exp((r - q) * h + v * np.sqrt(h))
    d = np.exp((r - q) * h - v * np.sqrt(h))
    pu = (np.exp((r - q) * h) - d) / (u - d)
    pd = 1.0 - pu
    disc = np.exp(-r * h)
    
    ## Arrays to store the spot prices and option values
    Ct = np.zeros((nodes, n+1))
    St = np.zeros((nodes, n+1))
    Dt = np.zeros((nodes, n+1))
    Bt = np.zeros((nodes, n+1))
    
    for i in range(nodes):
        St[i, n] = S * (u**(n-i)) * (d**i)
        Ct[i, n] = payoff(St[i, n], K)
    

    for t in range((n-1), -1, -1):
        for j in range(t+1):
            St[j, t] = St[j, t+1] / u
            Ct[j, t] = disc * ((pu * Ct[j, t+1]) + (pd * Ct[j+1, t+1]))
            Dt[j, t] = np.exp(-q * h) * (Ct[j, t+1] - Ct[j+1, t+1]) / (St[j, t] * (u - d))
            Bt[j, t] = np.exp(-r * h) * (((u * Ct[j+1, t+1]) - (d * Ct[j, t+1])) / ( u - d))
        
    if verbose:
        print(np.around(St, 3))
        print("\n")
        print(np.around(Ct, 3))
        print("\n")
        print(np.around(Dt, 3))
        print("\n")
        print(np.around(Bt, 3))
        print("\n")
                    
            
    return Ct[0,0]

def americanBinomPricerRecursive(S, K, r, v, q, T, n, payoff, verbose = True):
    nodes = n  + 1
    h = T / n
    u = np.exp((r - q) * h + v * np.sqrt(h))
    d = np.exp((r - q) * h - v * np.sqrt(h))
    pu = (np.exp((r - q) * h) - d) / (u - d)
    pd = 1.0 - pu
    disc = np.exp(-r * h)
    
    
    Ct = np.empty(nodes)
    St = np.empty(nodes)
    Dt = np.empty(nodes)
    
    for i in range(nodes):
        St[i] = S * (u ** (n - i)) * (d ** i)
        Ct[i] = payoff(St[i], K)
    
    if verbose:
        print(Ct)
        
    for t in range((n - 1), -1, -1):
        for j in range(t+1):
            Ct[j] = disc * (pu * Ct[j] + pd * Ct[j+1])
            St[j] = St[j] / u
            if type == "put":
                Ct[j] = np.maximum(Ct[j], K - St[j])
            else:
                Ct[j] = np.maximum(Ct[j], St[j] - K)
            print(Ct)
            
    return Ct[0]


## Functions Calls


In [241]:
#callPrc = euroBinomPricerRecursive(S, K, r, v, q, T, n, callPayoff, verbose = True)
#print(f"The European Call Premium: {callPrc : 0.3f}")

#callPrc = americanBinomPricerRecursive(S, K, r, v, q, T, n, callPayoff, verbose = True)
#print(f"The American Call Premium: {callPrc : 0.3f}")

#putPrc = americanBinomPricerRecursive(S, K, r, v, q, T, n, putPayoff, verbose = True)
#print(f"The American Put Premium: {putPrc : 0.3f}")

#putPrc = euroBinomPricerRecursive(S, K, r, v, q, T, n, putPayoff, verbose = True)
#print(f"The European Put Premium: {putPrc : 0.3f}")



## Problem 1

In [242]:
def euroBinomPricerRecursive(S, K, r, v, q, T, n, payoff, verbose = True):
    nodes = n  + 1
    h = T / n
    u = 1.3
    d = .8
    pu = (np.exp((r - q) * h) - d) / (u - d)
    pd = 1.0 - pu
    disc = np.exp(-r * h)
    
    ## Arrays to store the spot prices and option values
    Ct = np.zeros((nodes, n+1))
    St = np.zeros((nodes, n+1))
    Dt = np.zeros((nodes, n+1))
    Bt = np.zeros((nodes, n+1))
    
    for i in range(nodes):
        St[i, n] = S * (u**(n-i)) * (d**i)
        Ct[i, n] = payoff(St[i, n], K)
    

    for t in range((n-1), -1, -1):
        for j in range(t+1):
            St[j, t] = St[j, t+1] / u
            Ct[j, t] = disc * ((pu * Ct[j, t+1]) + (pd * Ct[j+1, t+1]))
            Dt[j, t] = np.exp(-q * h) * (Ct[j, t+1] - Ct[j+1, t+1]) / (St[j, t] * (u - d))
            Bt[j, t] = np.exp(-r * h) * (((u * Ct[j+1, t+1]) - (d * Ct[j, t+1])) / ( u - d))
        
    if verbose:
        print("spot Price Tree")
        print(np.around(St, 3))
        print("\n")
        print("Premium Tree")
        print(np.around(Ct, 3))
        print("\n")
        print("Delta Tree")
        print(np.around(Dt, 3))
        print("\n")
        print("B Tree")
        print(np.around(Bt, 3))
        print("\n")
                    
            
    return Ct[0,0], Dt[0,0], Bt[0,0]


S = 100
K = 105
r = 0.08
v = 0.30
q = 0.0
T = .5
n = 1
#type = "call"


## Problem 1a

In [243]:
callPrc, Dt, Bt = euroBinomPricerRecursive(S, K, r, v, q, T, n, callPayoff, verbose = True)
print(f"The European Call Premium: {callPrc : 0.3f}")
print(f"The European Call Delta: {Dt : 0.3f}")
print(f"The European Call B: {Bt : 0.3f}")


spot Price Tree
[[100. 130.]
 [  0.  80.]]


Premium Tree
[[11.568 25.   ]
 [ 0.     0.   ]]


Delta Tree
[[0.5 0. ]
 [0.  0. ]]


B Tree
[[-38.432   0.   ]
 [  0.      0.   ]]


The European Call Premium:  11.568
The European Call Delta:  0.500
The European Call B: -38.432


## Problem 1b

In [244]:
putPrc, Dt, Bt = euroBinomPricerRecursive(S, K, r, v, q, T, n, putPayoff, verbose = True)
print(f"The European Put Premium: {putPrc : 0.3f}")
print(f"The European Put Delta: {Dt : 0.3f}")
print(f"The European Put B: {Bt : 0.3f}")

spot Price Tree
[[100. 130.]
 [  0.  80.]]


Premium Tree
[[12.451  0.   ]
 [ 0.    25.   ]]


Delta Tree
[[-0.5  0. ]
 [ 0.   0. ]]


B Tree
[[62.451  0.   ]
 [ 0.     0.   ]]


The European Put Premium:  12.451
The European Put Delta: -0.500
The European Put B:  62.451


## Problem 2


## Problem 2a

In [245]:
S = 100
K = 95
r = 0.08
v = 0.30
q = 0.0
T = .5
n = 1
#type = "put"

putPrc, Dt, Bt = euroBinomPricerRecursive(S, K, r, v, q, T, n, putPayoff, verbose = True)
print(f"The European Put Premium: {putPrc : 0.3f}")
print(f"The European Put Delta: {Dt : 0.3f}")
print(f"The European Put B: {Bt : 0.3f}")

spot Price Tree
[[100. 130.]
 [  0.  80.]]


Premium Tree
[[ 7.471  0.   ]
 [ 0.    15.   ]]


Delta Tree
[[-0.3  0. ]
 [ 0.   0. ]]


B Tree
[[37.471  0.   ]
 [ 0.     0.   ]]


The European Put Premium:  7.471
The European Put Delta: -0.300
The European Put B:  37.471


## Problem  2B & 2C

In [246]:
callPrc, Dt, Bt = euroBinomPricerRecursive(S, K, r, v, q, T, n, callPayoff, verbose = True)
print(f"The European Call Premium: {callPrc : 0.3f}")
print(f"The European Call Delta: {Dt : 0.3f}")
print(f"The European Call B: {Bt : 0.3f}")

spot Price Tree
[[100. 130.]
 [  0.  80.]]


Premium Tree
[[16.196 35.   ]
 [ 0.     0.   ]]


Delta Tree
[[0.7 0. ]
 [0.  0. ]]


B Tree
[[-53.804   0.   ]
 [  0.      0.   ]]


The European Call Premium:  16.196
The European Call Delta:  0.700
The European Call B: -53.804


## 2b


Arbitrage = 17 - 16.196 = .804

## 2c

Arbitrage = 16.196 - 15.50 = .696

## Problem 3


In [247]:
S = 100
K = 95
r = 0.08
v = 0.30
q = 0.0
T = 1
n = 2
#type = "call"


callPrc, Dt, Bt = euroBinomPricerRecursive(S, K, r, v, q, T, n, callPayoff, verbose = True)
print(f"The Final European Call Premium: {callPrc : 0.3f}")
print(f"The Final European Call Delta: {Dt : 0.3f}")
print(f"The Final European Call B: {Bt : 0.3f}")

spot Price Tree
[[100. 130. 169.]
 [  0.  80. 104.]
 [  0.   0.  64.]]


Premium Tree
[[19.994 38.725 74.   ]
 [ 0.     4.165  9.   ]
 [ 0.     0.     0.   ]]


Delta Tree
[[0.691 1.    0.   ]
 [0.    0.225 0.   ]
 [0.    0.    0.   ]]


B Tree
[[-49.127 -91.275   0.   ]
 [  0.    -13.835   0.   ]
 [  0.      0.      0.   ]]


The Final European Call Premium:  19.994
The Final European Call Delta:  0.691
The Final European Call B: -49.127


## Problem 4

In [248]:
callPrc, Dt, Bt = euroBinomPricerRecursive(80, 95, .08, .3, 0, 1, 2, callPayoff, verbose = False)
print(f"The Final European Call Delta: {Dt : 0.3f}")
print(f"The Price of this Call Option was: 80")
print("\n")
callPrc, Dt, Bt = euroBinomPricerRecursive(90, 95, .08, .3, 0, 1, 2, callPayoff, verbose = False)
print(f"The Final European Call Delta: {Dt : 0.3f}")
print(f"The Price of this Call Option was: 90")
print("\n")
callPrc, Dt, Bt = euroBinomPricerRecursive(110, 95, .08, .3, 0, 1, 2, callPayoff, verbose = False)
print(f"The Final European Call Delta: {Dt : 0.3f}")
print(f"The Price of this Call Option was: 110")
print("\n")
callPrc, Dt, Bt = euroBinomPricerRecursive(120, 95, .08, .3, 0, 1, 2, callPayoff, verbose = False)
print(f"The Final European Call Delta: {Dt : 0.3f}")
print(f"The Price of this Call Option was: 120")
print("\n")
callPrc, Dt, Bt = euroBinomPricerRecursive(130, 95, .08, .3, 0, 1, 2, callPayoff, verbose = False)
print(f"The Final European Call Delta: {Dt : 0.3f}")
print(f"The Price of this Call Option was: 130")
print("\n")

The Final European Call Delta:  0.465
The Price of this Call Option was: 80


The Final European Call Delta:  0.587
The Price of this Call Option was: 90


The Final European Call Delta:  0.777
The Price of this Call Option was: 110


The Final European Call Delta:  0.849
The Price of this Call Option was: 120


The Final European Call Delta:  0.910
The Price of this Call Option was: 130




As the Stock Price increased, Delta increased.

## Problem 5

In [249]:
def americanBinomPricerRecursive(S, K, r, v, q, T, n, payoff, verbose = True):
    nodes = n  + 1
    h = T / n
    u = np.exp((r - q) * h + v * np.sqrt(h))
    d = np.exp((r - q) * h - v * np.sqrt(h))
    pu = (np.exp((r - q) * h) - d) / (u - d)
    pd = 1.0 - pu
    disc = np.exp(-r * h)
    
    
    Ct = np.empty(nodes)
    St = np.empty(nodes)
    Dt = np.empty(nodes)
    
    for i in range(nodes):
        St[i] = S * (u ** (n - i)) * (d ** i)
        Ct[i] = payoff(St[i], K)
    
    if verbose:
        print(Ct)
        
    for t in range((n - 1), -1, -1):
        for j in range(t+1):
            Ct[j] = disc * (pu * Ct[j] + pd * Ct[j+1])
            St[j] = St[j] / u
            if type == "put":
                Ct[j] = np.maximum(Ct[j], K - St[j])
            else:
                Ct[j] = np.maximum(Ct[j], St[j] - K)
            print(Ct)
            
    return Ct[0]

def euroBinomPricerRecursive(S, K, r, v, q, T, n, payoff, verbose = True):
    nodes = n  + 1
    h = T / n
    u = np.exp((r - q) * h + v * np.sqrt(h))
    d = np.exp((r - q) * h - v * np.sqrt(h))
    pu = (np.exp((r - q) * h) - d) / (u - d)
    pd = 1.0 - pu
    disc = np.exp(-r * h)
    
    ## Arrays to store the spot prices and option values
    Ct = np.zeros((nodes, n+1))
    St = np.zeros((nodes, n+1))

    for i in range(nodes):
        St[i, n] = S * (u**(n-i)) * (d**i)
        Ct[i, n] = payoff(St[i, n], K)
    

    for t in range((n-1), -1, -1):
        for j in range(t+1):
            St[j, t] = St[j, t+1] / u
            Ct[j, t] = disc * ((pu * Ct[j, t+1]) + (pd * Ct[j+1, t+1]))
        
    if verbose:
        print(np.around(St, 3))
        print("\n")
        print(np.around(Ct, 3))
        print("\n") 
            
    return Ct[0,0]

S = 100
K = 95
r = 0.08
v = 0.30
q = 0.0
T = 1
n = 3
type = "call"

## 5a

In [250]:
S = 100
K = 95
r = 0.08
v = 0.30
q = 0.0
T = 1
n = 3

type = "call"
callPrc = americanBinomPricerRecursive(S, K, r, v, q, T, n, callPayoff, verbose = True)
print(f"The American Call Premium: {callPrc : 0.3f}")

print(u,d)



[87.1417861 33.8147424  0.         0.       ]
[56.64406241 33.8147424   0.          0.        ]
[56.64406241 15.04032855  0.          0.        ]
[56.64406241 15.04032855  0.          0.        ]
[33.14931753 15.04032855  0.          0.        ]
[33.14931753  6.6897296   0.          0.        ]
[18.28255221  6.6897296   0.          0.        ]
The American Call Premium:  18.283
1.1454617381452392 0.8966038495199921


No Early Exercise

## 5b

In [251]:
 callPrc = euroBinomPricerRecursive(S, K, r, v, q, T, n, callPayoff, verbose = True)
print(f"The European Call Premium: {callPrc : 0.3f}")
S = 100
K = 95
r = 0.08
v = 0.30
q = 0.0
T = 1
n = 3
type = "call"

[[100.    122.125 149.144 182.142]
 [  0.     86.369 105.478 128.815]
 [  0.      0.     74.596  91.101]
 [  0.      0.      0.     64.428]]


[[18.283 33.149 56.644 87.142]
 [ 0.     6.69  15.04  33.815]
 [ 0.     0.     0.     0.   ]
 [ 0.     0.     0.     0.   ]]


The European Call Premium:  18.283


Because there was no dividend, the American Call option does not exercise early. The premium on the American call and European Call are the same

## 5c

In [252]:
putPrc = euroBinomPricerRecursive(S, K, r, v, q, T, n, putPayoff, verbose = True)
print(f"The European Put Premium: {putPrc : 0.3f}")
Fo = S * np.exp(r * T)
pv = (Fo - K) / ((1+ r) ** T)
print("If", callPrc - putPrc, " equals", pv, "put-call parity holds")

[[100.    122.125 149.144 182.142]
 [  0.     86.369 105.478 128.815]
 [  0.      0.     74.596  91.101]
 [  0.      0.      0.     64.428]]


[[ 5.979  1.091  0.     0.   ]
 [ 0.    10.387  2.062  0.   ]
 [ 0.     0.    17.904  3.899]
 [ 0.     0.     0.    30.572]]


The European Put Premium:  5.979
If 12.30394709326959  equals 12.341395155088758 put-call parity holds


## 5d

In [253]:
S = 100
K = 95
r = 0.08
v = 0.30
q = 0.0
T = 1
n = 3
type = "put"

In [254]:
putPrc = americanBinomPricerRecursive(S, K, r, v, q, T, n, putPayoff, verbose = True)
print(f"The American Put Premium: {putPrc : 0.3f}")
print("\n")
putPrc = euroBinomPricerRecursive(S, K, r, v, q, T, n, putPayoff, verbose = True)
print(f"The European Put Premium: {putPrc : 0.3f}")

[ 0.          0.          3.89933488 30.57157332]
[ 0.          0.          3.89933488 30.57157332]
[ 0.          2.06235672  3.89933488 30.57157332]
[ 0.          2.06235672 20.40351726 30.57157332]
[ 1.09077967  2.06235672 20.40351726 30.57157332]
[ 1.09077967 11.7087201  20.40351726 30.57157332]
[ 6.67790123 11.7087201  20.40351726 30.57157332]
The American Put Premium:  6.678


[[100.    122.125 149.144 182.142]
 [  0.     86.369 105.478 128.815]
 [  0.      0.     74.596  91.101]
 [  0.      0.      0.     64.428]]


[[ 5.979  1.091  0.     0.   ]
 [ 0.    10.387  2.062  0.   ]
 [ 0.     0.    17.904  3.899]
 [ 0.     0.     0.    30.572]]


The European Put Premium:  5.979


The American put is worth more because it can ecercise earlier to get a higher payoff.

## Problem 6


In [255]:
def americanBinomPricerRecursive(S, K, r, v, q, T, n, payoff, verbose = True):
    nodes = n  + 1
    h = T / n
    u = np.exp((r - q) * h + v * np.sqrt(h))
    d = np.exp((r - q) * h - v * np.sqrt(h))
    pu = (np.exp((r - q) * h) - d) / (u - d)
    pd = 1.0 - pu
    disc = np.exp(-r * h)
    
    
    Ct = np.empty(nodes)
    St = np.empty(nodes)
    Dt = np.empty(nodes)
    
    for i in range(nodes):
        St[i] = S * (u ** (n - i)) * (d ** i)
        Ct[i] = payoff(St[i], K)
    
    if verbose:
        print(Ct)
        
    for t in range((n - 1), -1, -1):
        for j in range(t+1):
            Ct[j] = disc * (pu * Ct[j] + pd * Ct[j+1])
            St[j] = St[j] / u
            if type == "put":
                Ct[j] = np.maximum(Ct[j], K - St[j])
            else:
                Ct[j] = np.maximum(Ct[j], St[j] - K)
            print(Ct)
            
    return Ct[0]

def euroBinomPricerRecursive(S, K, r, v, q, T, n, payoff, verbose = True):
    nodes = n  + 1
    h = T / n
    u = np.exp((r - q) * h + v * np.sqrt(h))
    d = np.exp((r - q) * h - v * np.sqrt(h))
    pu = (np.exp((r - q) * h) - d) / (u - d)
    pd = 1.0 - pu
    disc = np.exp(-r * h)
    
    ## Arrays to store the spot prices and option values
    Ct = np.zeros((nodes, n+1))
    St = np.zeros((nodes, n+1))

    for i in range(nodes):
        St[i, n] = S * (u**(n-i)) * (d**i)
        Ct[i, n] = payoff(St[i, n], K)
    

    for t in range((n-1), -1, -1):
        for j in range(t+1):
            St[j, t] = St[j, t+1] / u
            Ct[j, t] = disc * ((pu * Ct[j, t+1]) + (pd * Ct[j+1, t+1]))
        
    if verbose:
        print(np.around(St, 3))
        print("\n")
        print(np.around(Ct, 3))
        print("\n") 
            
    return Ct[0,0]


## 6a


In [256]:
S = 40
K = 40
r = 0.08
v = 0.30
q = 0.0
T = .5
n = 3
#type = "put"

putPrc = euroBinomPricerRecursive(S, K, r, v, q, T, n, putPayoff, verbose = True)
print("U is:",u,"D is:",d)

[[40.    45.818 52.483 60.118]
 [ 0.    35.864 41.081 47.057]
 [ 0.     0.    32.156 36.833]
 [ 0.     0.     0.    28.831]]


[[ 2.809  0.868  0.     0.   ]
 [ 0.     4.597  1.658  0.   ]
 [ 0.     0.     7.314  3.167]
 [ 0.     0.     0.    11.169]]


U is: 1.1454617381452392 D is: 0.8966038495199921


## 6b

In [257]:
callPrc = euroBinomPricerRecursive(S, K, r, v, q, T, n, callPayoff, verbose = False)
print(f"The European Call Premium: {callPrc : 0.3f}")
print("\n")
type = "call"
callPrc = americanBinomPricerRecursive(S, K, r, v, q, T, n, callPayoff, verbose = False)
print(f"The American Call Premium: {callPrc : 0.3f}")
print("\n")
type = "put"
putPrc = americanBinomPricerRecursive(S, K, r, v, q, T, n, putPayoff, verbose = False)
print(f"The American Put Premium: {putPrc : 0.3f}")
print("\n")
putPrc = euroBinomPricerRecursive(S, K, r, v, q, T, n, putPayoff, verbose = False)
print(f"The European Put Premium: {putPrc : 0.3f}")



The European Call Premium:  4.377


[13.01309727  7.05673217  0.          0.        ]
[13.01309727  3.26869392  0.          0.        ]
[13.01309727  3.26869392  0.          0.        ]
[7.73902974 3.26869392 0.         0.        ]
[7.73902974 1.51406624 0.         0.        ]
[4.37742951 1.51406624 0.         0.        ]
The American Call Premium:  4.377


[ 0.          0.          3.16660277 11.16886174]
[ 0.          1.65788424  3.16660277 11.16886174]
[ 0.          1.65788424  7.84406148 11.16886174]
[ 0.86799019  1.65788424  7.84406148 11.16886174]
[ 0.86799019  4.8747172   7.84406148 11.16886174]
[ 2.95422756  4.8747172   7.84406148 11.16886174]
The American Put Premium:  2.954


The European Put Premium:  2.809
